CREATE TABLE IF NOT EXISTS {schema}.{table} (
    ts_code TEXT PRIMARY KEY,
    group_name TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
