CREATE TABLE IF NOT EXISTS {schema}.{table} (
    ts_code TEXT NOT NULL,
    ann_date DATE,
    end_date DATE NOT NULL,
    eps DOUBLE PRECISION,
    gross_margin DOUBLE PRECISION,
    current_ratio DOUBLE PRECISION,
    quick_ratio DOUBLE PRECISION,
    invturn_days DOUBLE PRECISION,
    arturn_days DOUBLE PRECISION,
    inv_turn DOUBLE PRECISION,
    ar_turn DOUBLE PRECISION,
    netprofit_margin DOUBLE PRECISION,
    grossprofit_margin DOUBLE PRECISION,
    profit_to_gr DOUBLE PRECISION,
    saleexp_to_gr DOUBLE PRECISION,
    adminexp_of_gr DOUBLE PRECISION,
    finaexp_of_gr DOUBLE PRECISION,
    roe DOUBLE PRECISION,
    q_eps DOUBLE PRECISION,
    q_netprofit_margin DOUBLE PRECISION,
    q_gsprofit_margin DOUBLE PRECISION,
    q_roe DOUBLE PRECISION,
    basic_eps_yoy DOUBLE PRECISION,
    op_yoy DOUBLE PRECISION,
    ebt_yoy DOUBLE PRECISION,
    netprofit_yoy DOUBLE PRECISION,
    q_sales_yoy DOUBLE PRECISION,
    q_sales_qoq DOUBLE PRECISION,
    q_op_yoy DOUBLE PRECISION,
    q_op_qoq DOUBLE PRECISION,
    q_profit_yoy DOUBLE PRECISION,
    q_profit_qoq DOUBLE PRECISION,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ts_code, end_date)
);
