CREATE TABLE IF NOT EXISTS {schema}.{table} (
    symbol TEXT NOT NULL,
    ts_code TEXT,
    stock_name TEXT,
    industry TEXT,
    report_period DATE NOT NULL,
    announcement_date DATE,
    eps NUMERIC,
    revenue NUMERIC,
    revenue_prev NUMERIC,
    revenue_yoy NUMERIC,
    revenue_qoq NUMERIC,
    net_profit NUMERIC,
    net_profit_prev NUMERIC,
    net_profit_yoy NUMERIC,
    net_profit_qoq NUMERIC,
    net_assets_per_share NUMERIC,
    return_on_equity NUMERIC,
    row_number INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (symbol, report_period)
);
