CREATE TABLE IF NOT EXISTS {schema}.{table} (
    ts_code TEXT PRIMARY KEY,
    summary JSONB NOT NULL,
    model TEXT,
    generated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE {schema}.{table}
    ADD COLUMN IF NOT EXISTS model TEXT;

ALTER TABLE {schema}.{table}
    ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE {schema}.{table}
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP;
