CREATE TABLE IF NOT EXISTS {schema}.{table} (
    cal_date DATE PRIMARY KEY,
    exchange TEXT NOT NULL DEFAULT 'SSE',
    is_open BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
